language: node_js
node_js:
- 0.12.7
services:
- mongodb
before_install:
- npm install -g grunt-cli
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install:
- npm install
deploy:
  provider: heroku
  api_key:
    secure: R93n/ZvOuY4nAgLE/zmy+lVtb33g3Ot5pZj/06xauAIU07QqKl4VIwCi4yAC9NvsF9qbA/Ba8BD3YbJ0bmTEDqQf0oyIC/2xMzFg40RvcKJS6PyVHbo+9/ePqsaAphO4MG9uQ0yWmgQbZbJAQZJ960evs9Jj/p7ZA37hpriZ58rj6UG1XesgtvDZNY+zUKL94sVQLAZzAzHDqT0b8MEDEA3TFxxngaMtSlmDHHxwo8sxh7h8GxZbgI8gkZsPk9Hauxo+kvgaGx5WgEpSYEzbAsGc2m/EF6VqSIS06VjEwHFpo5sRhSZRdIUA78vX/4NJbWtmZJg5bR0p6O5HmVYtCzO2AHwDpTDXQrKXiHOjXwIA0zkHK89plo10O9f65u2zmm5wWBxp20UsyiKKN9k/QHZd9x2RAHIx9idz9Is1Y0mxpjyCUS3K5Le/i5bWhxZJNo6lDNSRfdMp0lq/XbQUcPXnQflg3/o/MoubdQZKo7uxC6lSy2n2+GNGO4Qp9YyPr/UXoOH4wo3joOm5aKkTEiu1+No5b5xwYBN0YXjs+17jtuNvSWBs7yC03m0JXFt83sw6c9toMlI33T0sOBn7Oa/9MSBt/ye4Ht5ZVYOJGdjpkqAC1vFYaFTTMWXceOCyG7MR/Hc0stZMlx8Fw32DO3a65MhNLxScCGoV43pu3vk=
  app: habit-trainer
  on:
    repo: habittracker/greenfield-apollo
    branch: staging
