language: node_js
node_js:
- 0.12.7
services:
- mongodb
before_install:
- npm install -g grunt-cli
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install:
- npm install
deploy:
  provider: heroku
  api_key:
    secure: nm5AQFKsuvrtCgYao6EtV1IGPieXxw3mnZgwZV1OCQnmtIoVsfTwFtynfHYUuKX5QeQMQiLmjUAQdR1WhFQcVE3k8Wj0MmCSND9vvCtVOQdroKlsdoiesoVxn1FfWMXes0ZTP58AH8IMu5ojsR+l+bKuIr1BsX9SRH0PZo5tHnIQNcFNX748FBLpTHxrJnZgUHhH8kGidiuOjGZ9mnJFDSpoALlzHlZGoHKWjqKB3QnZ+LA7EcCYUTmg8FbEd9fHMBHyBTMDMGHINArvQ2D3xkNBxtXBvc84uGMJX2HbusP3/mRHpf0nYUrZZC7H4mozaEP+URoDczmj8pNqQzfzzYZo5EZM7MPKBM//9w8pzVcRkKnpvnaKZUHJcDSA7FRGyYgLCvFyefmTsEaURIEsX2P4pvOQncsuWKgEkrGJDTxnK0Ue7IAhsaThtkZ/xkNdaeqjRf0eZo1/UmdufPzPUwbGFy+fWUaJmZ8GWuTYltjCrHFlIRzJCrncJM7b0LDL8olZstNRKUHmvxxSiztqaj6J2ZFweuToP+I2nE8jkn1CJ/BR28mHxeHR1ex6ClNiokCeVjNZWPukL8ZxvVdD5LCN3hvPTcvDb5YYoC+Z8Hue5PUZrLG411/Xoj1cSQRLHFZRovnw29rYwt9l6byRzds+AMtDumxN+E3okO2V8BU=
    app: habit-trainer
  on:
    repo: habittracker/greenfield-apollo
    branch: staging
